# Generated by Django 4.2.2 on 2023-07-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table1',
            new_name='stu1',
        ),
    ]
