# Generated by Django 4.2.2 on 2023-07-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_rename_table1_stu1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stu1',
        ),
    ]
