# Generated by Django 4.2.2 on 2023-06-30 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 6, 30, 7, 39, 10, 420522, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
