# Generated by Django 4.2.2 on 2023-06-30 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_table1_datetime_alter_table1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 7, 58, 30, 748202, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='table1',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
