# Generated by Django 4.1.6 on 2023-07-03 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_table3_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 20, 13, 863185, tzinfo=datetime.timezone.utc)),
        ),
    ]
