# Generated by Django 4.2.2 on 2023-07-03 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_table4_alter_table1_datetime_alter_table3_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='table5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 23, 16, 26, 854427, tzinfo=datetime.timezone.utc)),
        ),
    ]
