# Generated by Django 4.2.2 on 2023-07-04 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_table5_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 3, 50, 49, 378107, tzinfo=datetime.timezone.utc)),
        ),
    ]
