# Generated by Django 4.2.2 on 2023-07-06 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 9, 25, 12, 41904, tzinfo=datetime.timezone.utc)),
        ),
    ]
