# Generated by Django 4.2.2 on 2023-07-07 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_table6_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 9, 20, 36, 416254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='table6',
            name='surname',
            field=models.CharField(default='itkare', max_length=50),
        ),
    ]
