# Generated by Django 4.2.3 on 2023-07-09 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_table1_datetime_alter_table6_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 8, 13, 8, 884294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='table6',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
