# Generated by Django 4.2.3 on 2023-07-11 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 13, 51, 41, 204736)),
        ),
    ]
