# Generated by Django 4.2.2 on 2023-07-15 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_table1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 9, 0, 44, 241979)),
        ),
    ]
